# Generated by Django 5.0 on 2023-12-18 06:41

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
