# Generated by Django 5.0 on 2023-12-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='search_vector',
        ),
    ]
