# Generated by Django 5.0 on 2023-12-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_email',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='password',
        ),
    ]
