# Generated by Django 5.0 on 2023-12-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_artist_email_remove_artist_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$rRZqpHKM6mKCw1K8MyXrj1$YUyBQjdpvEoy1aVrDUgmI+t4LdvJfocl6xCtH3HbvgE='),
        ),
    ]
