# Generated by Django 5.0 on 2023-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='password',
            field=models.CharField(max_length=350),
        ),
    ]
